apiVersion: batch/v1
kind: CronJob
metadata:
  name: kronos-update
  namespace: default
spec:
  schedule: "* 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kronos-update
            image: ghcr.io/srajasimman/kronos_worklog_update:main
            envFrom:
            - secretRef:
                name: kronos-secret
          restartPolicy: OnFailure
